server:
  port: 8080
spring:
  application:
    name: user-manager
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    password: admin
    username: admin
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=false;
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  #    config-url: /user-account-management/openapi/swagger-config
  #    url: /user-account-management/openapi
  api-docs:
    path: /openapi
